"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateChallenge = generateChallenge;
exports.verifySupportCode = verifySupportCode;
exports.getSecret = getSecret;
const crypto = __importStar(require("crypto"));
// Use a fixed secret for this application instance. 
// In a real production app, this might be more obscured or environment-based,
// but for this implementation, a hardcoded secret in main process is acceptable per plan.
const APP_SECRET = 'SAMBAD_CAMPAIGN_MANAGER_SECURE_UNLOCK_KEY_2025';
// Store current challenges in memory to verify they were generated by us
// Map<ChallengeCode, Timestamp>
const activeChallenges = new Map();
// Clean up old challenges every hour
setInterval(() => {
    const now = Date.now();
    for (const [code, timestamp] of activeChallenges.entries()) {
        if (now - timestamp > 3600000) { // 1 hour expiration
            activeChallenges.delete(code);
        }
    }
}, 3600000);
/**
 * Generates a short, readable random code (e.g., "REQ-A1B2")
 */
function generateChallenge() {
    const randomBytes = crypto.randomBytes(4);
    const code = 'REQ-' + randomBytes.toString('hex').toUpperCase().substring(0, 4);
    // Store valid challenge with timestamp
    activeChallenges.set(code, Date.now());
    return code;
}
/**
 * Verifies if the provided response key matches the challenge using HMAC
 */
function verifySupportCode(challenge, response) {
    if (!challenge || !response)
        return false;
    // 1. Verify challenge exists and is recent (prevent replay of very old codes if logic changes)
    if (!activeChallenges.has(challenge)) {
        // We might allow verifying even if not in map for statelessness if needed,
        // but checking map prevents users from just using any string as challenge.
        // However, for the tool to work simpler, we can relax this if needed.
        // Let's stick to strict map check for security.
        return false;
    }
    // 2. Generate expected response
    // Logic: HMAC-SHA256(challenge, APP_SECRET) -> truncated to 8 chars or similar
    const hmac = crypto.createHmac('sha256', APP_SECRET);
    hmac.update(challenge);
    const fullHash = hmac.digest('hex').toUpperCase();
    // We use a prefix plus part of the hash as the key
    // e.g., "UNLOCK-" + first 8 chars of hash
    const expectedResponse = 'UNLOCK-' + fullHash.substring(0, 8);
    return response === expectedResponse;
}
/**
 * Helper to get the secret (Only for the generator script, theoretically)
 * In the main app, we just use it internally.
 */
function getSecret() {
    return APP_SECRET;
}
//# sourceMappingURL=supportService.js.map